_target_: transformers.TrainingArguments
output_dir: "."
learning_rate: 1e-3
gradient_checkpointing: false
gradient_accumulation_steps: 16
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
adam_beta1: 0.9
adam_beta2: 0.95
adam_epsilon: 1e-12
weight_decay: 0.001
eval_steps: 500
save_steps: 500
num_train_epochs: 3
logging_steps: 10
max_grad_norm: 1.0
save_total_limit: 4
fp16: false
lr_scheduler_type: cosine
warmup_ratio: 0.15
evaluation_strategy: steps
