databricks/databricks-dolly-15k:
  prompt: instruction
  context: context
  response: response

Dahoas/cot_gsm8k:
  prompt: question
  response: answer

psmathur/WizardLM_Orca:
  prompt: instruction
  response: output